language: ruby
cache: bundler
rvm:
- 2.2.2
branches:
  only:
  - master
script:
- bundle exec jekyll build
deploy:
  provider: s3
  bucket: baayywhaztsvtqiytvdq
  skip_cleanup: true
  region: "eu-west-1"
  local_dir: _site
  on:
    branch: master
  dot_match: true
  access_key_id:
    secure: "hljn7mA2y6YK5JOxB0kTQmngNy7Q66Au5St0u1zE5Lb8+SJFyKIsKqBkoktP7l0Ve5WIuFc832dAor9IKkp5gsguFVND9AIzmxiBIM6Y1dkuJvCCkBycjmcsFicQI3vjbfF8J5STi+5Qvlbo4cyK7MiDeneLEa5LbX4hLfSyMWJDgXgFyoU4QsNGP+ksiL0ugSqAosgNQfAVM5qnDX3jwJSlmJupC3Ag1wfyq8nJY3p7meC+3TQp816QT1Yx2GJI5dTXa/I8w76gMd8AvFo6W8Vc4gKP+1nQHYesLTW+brjNfiPT8Yyl4/oDMyWY3Ijf7dmmb+8QZGfvYbAK4ZPc1iFjdyV4GMIvdjYRNvlEhNGXLu9wraQm+Cz8sIecMPP07rFCIrL8NcEbo5XRT9bV5XV+/RWCiyh9guQ2FStsCYSjT2bR4EB1zZEcIGr9CIklCYBjnjn8xCL1+gzCYpr2rzlt05WLDDMhvJajaViTaP3sP9M937B3n3xUO4JsqeWc3TQ88Sh+Invg4/1YmNOW5PhaRDOaS3sjRcM0pyTDRltphWpaWNnx8kBRW+dLo2mhU811Laexi6GFsImJoV+CjBW5giNYHPMMV7PXai04R+UDAvHH7h1XahFkBTabr01pNNK+0FlrXR1l7/JKal3siEbOaQDe6A6Kn+s+/OO/Svk="
  secret_access_key:
    secure: "Qj+d2V4c7AK/jMbqiAv8zOhPKygN2Od389hw1VpBi5CQBnqc/zDwnt2/KiFRf/LBi1Ozcj89UmFhPt8yflXTp/+Th8KFpDavVIN1tZAgo0BUdYgpVxOLyntaS3aUb9za3Bcc3rt5Mj+PFszV6Zv/16Gu+uvb46A4ZsZhQCcZDR2hMgzBnFVwdYbY3L7tI5HTDYMH3xJ9p2usqZyPriiiHDqNRN0B5adDitPGgHQakFgRuamsIoKu1EiiMUaViBas+8G7tz7Oh0Oq6auE5E+U1i1BhHGDxNz96WrVHOzPnUV2ZzRGpnbfXTaSyGW6Z5UESX+Zve0N2ee8wDwfJNNF8Vq6PzxQjbjpNK3HWPZcUxqjhzoZviYtcnkY6a1SpjNlUThs0P9xTKEKLWTclE3aeJviV5re5t8/qD/2aVHXkR2G0GCFCONrZoouo+zNJUNYGFlqZvs+VxgX3alYaqbNHHYs5HEexyg9OkcTyL8fOAYw5zUuq8dXIaLs22e2rBercLFZZSWjTCaxh/Q/AF1xsGmfFR4OVccQY57uZZsnKzlzfHnFO/R42hJm5IgeFgdiYz4fu2uR+JzaVFwmHEhej3ZhV9Xr0Lnr0K8Ccj3AzCsSfMJdy8PiRlV8ANNRaWvCFpVnrggmSUH+ooUdheUov6OhTApJuhrn/GFGr8/qwTY="
