language: ruby

cache: bundler

rvm:
- 2.2.2

branches:
  only:
  - master

script:
- bundle exec jekyll build

deploy:
  provider: s3
  bucket: baayywhaztsvtqiytvdq # Update this
  skip_cleanup: true
  region: eu-west-1         # Or whatever region you use
  local_dir: _site
  on:
    branch: master          # You can use another branch if you want
  dot_match: true